s='ATCATAAAGAGCCGGTGTCTCACATCAAAGGTGTAGTGATTAGCTGCTCGCAAGAAGAACGTCTCACAATCTCCTGTCGGTCCACAGAACCCAACCCCGAACTAAATCCCCCCAGCGCCGGAACAAAATACTGGCGAAAGACTTATCCCTTCTGCCAAAATTGAACATACGTGCTCAGGGAGCGTTCGTAGAATGTCGGAGAGCCCTACTGCGCGGACATGTCCAGCCTGACATGACGGCAAAGAGTAGAATTCATTAACGCCAGTAGACTCGCGAGGTTGCACCCGTCATGCCCTGCCCGGGCAAAGTAGGTGGCACGGGCCGTGTTGTGAAGCGAATAGGCTGGGAGGGAAGAATTAGGTGTGCACGGGAGCTCTCTTCCATCCGCATTAGCAGACATCGTATATTGTCGGTTGAGGTAGACAGCCTGATTATGTCAGAAAGGTGCTCTACGAGACCGACGAGTACTAACAATTGAACAGCATATGTGCGGGTTGAATTACCGCCTCCGCCCACTCCGCGAAATAACAACATGGTCGGGGATAGATTACGGACGATTTGTCCGAAACCGTGTGTTACCCACAATATACCCGGTGCCACGCATTGAAAGAAATGGAGACCCGGGGCATCGCCAGTGTGTAGCTGCAGTACAACCCCTTCCCCGAGACTTATCGTATGGCTAAACAAGCTTACTTAGCAGTTTCGGATGCGCCCTAATGCGAGCCTCGTGCAGTCCTACGACACCGCGAGCGGTGCCCACAATATCTCGTTATTACTGATGGCCAATCCTCGCGAATTAGAGTCCCGTCTTCCAAAGGCCTCACAATGGCCCTGAATAATTATCCTTAGACACCAGCATACTGGGATTCGCCTAAACTATTATTACTTATACCGTCAAGAAGGCGGAG'
reverse = s[::-1]
sc=''
for n in reverse:
    if n == 'A':
        sc+='T'
    elif n == 'T':
        sc+='A'
    elif n == 'G':
        sc+='C'
    else:
        sc+='G'
print sc
